# Python 201 - Assignment 01

## Q1:  Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.



In [ ]:
a = np.full((8,8),1)
print(a) 

a[::2, ::2] = 0
a[1::2, 1::2] = 0
a
#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

In [5]:
# Ans: Syntax of 2D Array Slicing:   array[start_row:stop_row:step_row, start_column:stop_column:step_column]
import numpy as np

a = np.zeros((8,8), dtype=int)
a[::2, ::2] = 0
a[1::2, 1::2] = 0
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)




[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Q2: Create a 2d array with 1 on the border and 0 inside

In [6]:
# Ans:
matrix = np.ones((8,8), dtype=int)
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


## Q3: Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
# Ans
a = np.arange(0,9)
b = a.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Q4: Create a vector with values ranging from 10 to 49 and then reverse the vector.

In [8]:
# Ans
a = np.arange(10,50)
a = np.flip(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Q5: Find indices of non-zero elements from the numpy array - [1,2,0,0,4,0]


In [9]:
arr = np.array([1, 2, 0, 0, 4, 0])


indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4], dtype=int64),)


## Q6 Wrire a recursive function that generates Fibonacci sequence of n numbers. For example, first 10 (n = 10) numbers in the sequence are  0, 1, 1, 2, 3, 5, 8, 13, 21, 34

In [10]:
def fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        sequence = fibonacci(n - 1)
        sequence.append(sequence[-1] + sequence[-2])
        return sequence

# Generate Fibonacci sequence for n = 10
n = 10
fib_seq = fibonacci(n)

# Print the Fibonacci sequence
print(" ".join(str(num) for num in fib_seq))

0 1 1 2 3 5 8 13 21 34


## Q7. Check whether a number is even or odd using lambda function

In [11]:
number = 5

result = (lambda x: "Even number" if x % 2 == 0 else "Odd number")(number)

print(result)


Odd number
